export const watches = [
  {
    id: "1",
    name: "Submariner Date",
    brand: "G-Shock",
    price: 12500000,
    originalPrice: 2000000,
    category: ["luxury", "sports"],
    rating: 4.9,
    reviewCount: 342,
    description:
      "ساعت غواصی افسانه‌ای جی شاک با طراحی اسپورت و عملکرد بی‌نظیر. مقاوم در برابر آب تا 300 متر.",
    features: [
      "کرونومتر",
      "تاریخ نمایش",
      "ضد آب 300 متر",
      "شیشه یاقوت ضد خش",
      "چرخش یک‌طرفه",
    ],
    image: "./images/6.png",
    colors: [
      { name: "مشکی", value: "#000000", stock: 5 },
      { name: "طلایی", value: "#D4AF37", stock: 2 },
      { name: "نقره‌ای", value: "#C0C0C0", stock: 8 },
    ],
    movement: "automatic",
    caseMaterial: "Oystersteel",
    strapMaterial: "چرم آلگاتور",
    waterResistance: "300 متر",
    diameter: 41,
    thickness: 12.5,
    weight: 155,
    powerReserve: "48 ساعت",
    warranty: "5 سال",
    inStock: true,
    isNew: true,
    isFeatured: true,
    isLimited: true,
    stockCount: 15,
    tags: ["پرطرفدار", "کلکسیونی", "سرمایه‌گذاری"],
    specifications: {
      کالیبر: "3235",
      فرکانس: "28,800 vph",
      ساختار: "کامل‌اتوماتیک",
      گواهی: "سوپرلاتیو کرونومتر",
      نور: "Chromalight",
    },
    sku: "ROLEX-SUB-2024",
  },
  {
    id: "2",
    name: "nautilus",
    brand: "Patek philippe",
    price: 40000000,
    originalPrice: 65000000,
    category: ["luxury", "sports"],
    rating: 4.9,
    reviewCount: 342,
    description:
      "ساعت غواصی افسانه‌ای رولکس با طراحی کلاسیک و عملکرد بی‌نظیر. مقاوم در برابر آب تا 300 متر.",
    features: [
      "کرونومتر",
      "تاریخ نمایش",
      "ضد آب 300 متر",
      "شیشه یاقوت ضد خش",
      "چرخش یک‌طرفه",
    ],
    image: "./images/2.png",
    colors: [
      { name: "مشکی", value: "#000000", stock: 5 },
      { name: "طلایی", value: "#D4AF37", stock: 2 },
      { name: "نقره‌ای", value: "#C0C0C0", stock: 8 },
    ],
    movement: "automatic",
    caseMaterial: "Oystersteel",
    strapMaterial: "چرم آلگاتور",
    waterResistance: "300 متر",
    diameter: 41,
    thickness: 12.5,
    weight: 155,
    powerReserve: "48 ساعت",
    warranty: "5 سال",
    inStock: true,
    isNew: true,
    isFeatured: true,
    isLimited: true,
    stockCount: 15,
    tags: ["پرطرفدار", "کلکسیونی", "سرمایه‌گذاری"],
    specifications: {
      کالیبر: "3235",
      فرکانس: "28,800 vph",
      ساختار: "کامل‌اتوماتیک",
      گواهی: "سوپرلاتیو کرونومتر",
      نور: "Chromalight",
    },
    sku: "ROLEX-SUB-2024",
  },
  {
    id: "3",
    name: "Royal Oak",
    brand: "Audemars Piguet",
    price: 120000000,
    originalPrice: 145000000,
    category: ["luxury", "sports"],
    rating: 4.9,
    reviewCount: 342,
    description:
      "ساعت افسانه‌ای رولکس با طراحی کلاسیک و عملکرد بی‌نظیر. مقاوم در برابر آب تا 300 متر.",
    features: [
      "کرونومتر",
      "تاریخ نمایش",
      "ضد آب 300 متر",
      "شیشه یاقوت ضد خش",
      "چرخش یک‌طرفه",
    ],
    image: "./images/3.png",
    colors: [
      { name: "مشکی", value: "#000000", stock: 5 },
      { name: "طلایی", value: "#D4AF37", stock: 2 },
      { name: "نقره‌ای", value: "#C0C0C0", stock: 8 },
    ],
    movement: "automatic",
    caseMaterial: "Oystersteel",
    strapMaterial: "چرم آلگاتور",
    waterResistance: "300 متر",
    diameter: 41,
    thickness: 12.5,
    weight: 155,
    powerReserve: "48 ساعت",
    warranty: "5 سال",
    inStock: true,
    isNew: true,
    isFeatured: true,
    isLimited: true,
    stockCount: 15,
    tags: ["پرطرفدار", "کلکسیونی", "سرمایه‌گذاری"],
    specifications: {
      کالیبر: "3235",
      فرکانس: "28,800 vph",
      ساختار: "کامل‌اتوماتیک",
      گواهی: "سوپرلاتیو کرونومتر",
      نور: "Chromalight",
    },
    sku: "ROLEX-SUB-2024",
  },
  {
    id: "4",
    name: "R 011",
    brand: "Richard Mille",
    price: 1250000000,
    originalPrice: 1450000000,
    category: ["luxury", "sports"],
    rating: 4.9,
    reviewCount: 342,
    description:
      "ساعت غواصی افسانه‌ای رولکس با طراحی کلاسیک و عملکرد بی‌نظیر. مقاوم در برابر آب تا 300 متر.",
    features: [
      "کرونومتر",
      "تاریخ نمایش",
      "ضد آب 300 متر",
      "شیشه یاقوت ضد خش",
      "چرخش یک‌طرفه",
    ],
    image: "./images/4.png",
    colors: [
      { name: "مشکی", value: "#000000", stock: 5 },
      { name: "طلایی", value: "#D4AF37", stock: 2 },
      { name: "نقره‌ای", value: "#C0C0C0", stock: 8 },
    ],
    movement: "automatic",
    caseMaterial: "Oystersteel",
    strapMaterial: "چرم آلگاتور",
    waterResistance: "300 متر",
    diameter: 41,
    thickness: 12.5,
    weight: 155,
    powerReserve: "48 ساعت",
    warranty: "5 سال",
    inStock: true,
    isNew: true,
    isFeatured: true,
    isLimited: true,
    stockCount: 15,
    tags: ["پرطرفدار", "کلکسیونی", "سرمایه‌گذاری"],
    specifications: {
      کالیبر: "3235",
      فرکانس: "28,800 vph",
      ساختار: "کامل‌اتوماتیک",
      گواهی: "سوپرلاتیو کرونومتر",
      نور: "Chromalight",
    },
    sku: "ROLEX-SUB-2024",
  },

  // ... 5 محصول دیگر با همین جزئیات کامل
];

export const filters = {
  brands: [
    "Rolex",
    "Omega",
    "Patek Philippe",
    "Audemars Piguet",
    "Cartier",
    "Tag Heuer",
    "Breitling",
    "IWC",
  ],
  categories: [
    "luxury",
    "sports",
    "dress",
    "digital",
    "smart",
    "vintage",
    "limited",
  ],
  movements: ["automatic", "quartz", "manual", "solar", "smart"],
  materials: ["استیل", "تیتانیوم", "طلای 18K", "سرامیک", "کربن"],
  priceRanges: [
    { label: "زیر 500 میلیون", min: 0, max: 500000000 },
    { label: "500 میلیون تا 1 میلیارد", min: 500000000, max: 1000000000 },
    { label: "1 تا 2 میلیارد", min: 1000000000, max: 2000000000 },
    { label: "بالای 2 میلیارد", min: 2000000000, max: 5000000000 },
  ],
};

export const initialFilters = {
  brands: [],
  categories: [],
  priceRange: [0, 5000000000],
  movements: [],
  materials: [],
  inStock: false,
  isNew: false,
  isLimited: false,
  search: "",
};
